FROM node:20-alpine AS builder
WORKDIR /app/platform/portal
COPY platform/portal/package*.json ./
RUN npm install
COPY platform/portal/ .
RUN npm run build

FROM nginx:stable
RUN rm /etc/nginx/conf.d/default.conf
COPY --from=builder /app/platform/portal/dist/portal/browser /usr/share/nginx/html
COPY platform/portal/nginx.public.conf /etc/nginx/conf.d/default.conf
COPY docs /usr/share/nginx/html/docs
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
