server {
    listen 80;
    server_name platform.pratyushes.dev;
    root /usr/share/nginx/html;
    index index.html;
    aio off;

    location ~ \.md$ {
        add_header Content-Type text/markdown;
        try_files $uri =404;
    }

    location = / {
        try_files $uri $uri/ /index.html;
    }

    location /landing {
        try_files $uri $uri/ /index.html;
    }

    location /docs {
        try_files $uri $uri/ /index.html;
    }

    location /assets {
        try_files $uri =404;
    }

    location / {
        return 404;
    }
}
