server {
    listen 80;
    server_name platform.pratyushes.dev;

    root /usr/share/nginx/html;
    index index.html;

    location = /health {
        access_log off;
        default_type text/plain;
        return 200 "OK\n";
    }

    location ~ \.md$ {
        default_type text/markdown;
        try_files $uri =404;
    }

    location /assets/ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
