apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-portal
  namespace: platform
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  rules:
  - host: platform.pratyushes.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: public-portal
            port:
              number: 80
  tls:
  - hosts:
    - platform.pratyushes.dev
    secretName: platform-pratyushes-dev-tls
