package config

import (
	"crypto/rand"
	"encoding/base64"
	"fmt"
	"os"
	"strings"

	"github.com/fatih/color"
	"golang.org/x/term"
)

// DefaultImageTag is set at link time by GoReleaser (e.g. "1.2.3").
// Falls back to "latest" for local/dev builds.
var DefaultImageTag = "latest"

type Config struct {
	Domain       string
	AdminEmail   string
	PlatformName string

	NonInteractive bool
	SkipK8s        bool
	SkipPreflight  bool

	ImageRegistry string
	ImageTag      string
	RepoURL       string
	GitHubToken   string

	InstallArgoCD      bool
	InstallMonitoring  bool
	InstallPortainer   bool
	InstallInfisical   bool
	InstallCertManager bool

	PostgresPassword  string
	MongoPassword     string
	RedisPassword     string
	MinioAccessKey    string
	MinioSecretKey    string
	JWTSecret         string
	WebhookSecret     string
	ArgoCDPassword    string
	GrafanaPassword   string
	InfisicalEncKey   string
	InfisicalJWT      string
	PortainerPassword string
	LEEmail           string
}

func Load() *Config {
	tagDefault := DefaultImageTag
	if tagDefault == "" {
		tagDefault = "latest"
	}
	c := &Config{
		PlatformName:       "Platform",
		ImageRegistry:      getEnv("PLATFORM_IMAGE_REGISTRY", "ghcr.io/mpratyush54"),
		ImageTag:           getEnv("PLATFORM_IMAGE_TAG", tagDefault),
		RepoURL:            getEnv("PLATFORM_REPO_URL", "https://github.com/Mpratyush54/SERVER-automation"),
		GitHubToken:        getEnv("GITHUB_TOKEN", ""),
		Domain:             os.Getenv("DOMAIN"),
		AdminEmail:         os.Getenv("ADMIN_EMAIL"),
		NonInteractive:     os.Getenv("NON_INTERACTIVE") == "true" || os.Getenv("PLATFORMCTL_AUTO") == "true",
		SkipK8s:            os.Getenv("SKIP_K8S") == "true",
		SkipPreflight:      os.Getenv("SKIP_PREFLIGHT") == "true",
		InstallArgoCD:      getEnvBool("INSTALL_ARGOCD", true),
		InstallMonitoring:  getEnvBool("INSTALL_MONITORING", true),
		InstallPortainer:   getEnvBool("INSTALL_PORTAINER", true),
		InstallInfisical:   getEnvBool("INSTALL_INFISICAL", true),
		InstallCertManager: getEnvBool("INSTALL_CERTMANAGER", true),
		MinioAccessKey:     getEnv("MINIO_ACCESS_KEY", "platformadmin"),
	}
	return c
}

func (c *Config) PromptInteractive() error {
	if c.NonInteractive {
		return nil
	}

	ask("Enter your domain (e.g., platform.example.com or 148.113.59.97.sslip.io)", &c.Domain, "")
	ask("Enter admin email for Let's Encrypt", &c.AdminEmail, "admin@dev.io")
	ask("Enter platform name", &c.PlatformName, "Platform")
	c.LEEmail = c.AdminEmail

	return nil
}

func ask(prompt string, target *string, defaultVal string) {
	if *target != "" {
		return
	}
	fmt.Print(color.CyanString("  ? " + prompt))
	if defaultVal != "" {
		fmt.Print(color.YellowString(" [%s]", defaultVal))
	}
	fmt.Print(": ")
	var input string
	fmt.Scanln(&input)
	if input == "" {
		input = defaultVal
	}
	*target = input
}

func askSecret(prompt string, target *string) {
	if *target != "" {
		return
	}
	fmt.Print(color.CyanString("  ? " + prompt + ": "))
	byteInput, _ := term.ReadPassword(int(os.Stdin.Fd()))
	fmt.Println()
	*target = string(byteInput)
}

func (c *Config) GenerateSecrets() {
	if c.PostgresPassword == "" {
		c.PostgresPassword = generatePassword(24)
	}
	if c.MongoPassword == "" {
		c.MongoPassword = generatePassword(24)
	}
	if c.RedisPassword == "" {
		c.RedisPassword = generatePassword(24)
	}
	if c.MinioSecretKey == "" {
		c.MinioSecretKey = generatePassword(32)
	}
	if c.JWTSecret == "" {
		c.JWTSecret = generatePassword(48)
	}
	if c.WebhookSecret == "" {
		c.WebhookSecret = generatePassword(32)
	}
	if c.ArgoCDPassword == "" {
		c.ArgoCDPassword = generatePassword(20)
	}
	if c.GrafanaPassword == "" {
		c.GrafanaPassword = generatePassword(20)
	}
	if c.InfisicalEncKey == "" {
		c.InfisicalEncKey = generatePassword(64)
	}
	if c.InfisicalJWT == "" {
		c.InfisicalJWT = generatePassword(48)
	}
	if c.PortainerPassword == "" {
		c.PortainerPassword = generatePassword(20)
	}
	if c.LEEmail == "" {
		c.LEEmail = c.AdminEmail
	}
	if c.LEEmail == "" {
		c.LEEmail = "admin@dev.io"
	}
	if c.AdminEmail == "" {
		c.AdminEmail = "admin@dev.io"
	}
	if c.Domain == "" {
		c.Domain = "localhost"
	}
}

func (c *Config) SaveEnvFile(path string) error {
	if idx := strings.LastIndexAny(path, "/\\"); idx != -1 {
		dir := path[:idx]
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("create config dir: %w", err)
		}
	}
	var b strings.Builder
	b.WriteString("# Platform configuration generated by platformctl\n")
	b.WriteString(fmt.Sprintf("DOMAIN=%s\n", c.Domain))
	b.WriteString(fmt.Sprintf("ADMIN_EMAIL=%s\n", c.AdminEmail))
	b.WriteString(fmt.Sprintf("PLATFORM_NAME=%s\n", c.PlatformName))
	b.WriteString(fmt.Sprintf("POSTGRES_PASSWORD=%s\n", c.PostgresPassword))
	b.WriteString(fmt.Sprintf("MONGO_PASSWORD=%s\n", c.MongoPassword))
	b.WriteString(fmt.Sprintf("REDIS_PASSWORD=%s\n", c.RedisPassword))
	b.WriteString(fmt.Sprintf("MINIO_ACCESS_KEY=%s\n", c.MinioAccessKey))
	b.WriteString(fmt.Sprintf("MINIO_SECRET_KEY=%s\n", c.MinioSecretKey))
	b.WriteString(fmt.Sprintf("JWT_SECRET=%s\n", c.JWTSecret))
	b.WriteString(fmt.Sprintf("PLATFORM_WEBHOOK_SECRET=%s\n", c.WebhookSecret))
	b.WriteString(fmt.Sprintf("ARGOCD_PASSWORD=%s\n", c.ArgoCDPassword))
	b.WriteString(fmt.Sprintf("GRAFANA_PASSWORD=%s\n", c.GrafanaPassword))
	b.WriteString(fmt.Sprintf("INFISICAL_ENCRYPTION_KEY=%s\n", c.InfisicalEncKey))
	b.WriteString(fmt.Sprintf("INFISICAL_JWT_SECRET=%s\n", c.InfisicalJWT))
	b.WriteString(fmt.Sprintf("PORTAINER_ADMIN_PASSWORD=%s\n", c.PortainerPassword))
	return os.WriteFile(path, []byte(b.String()), 0600)
}

func getEnv(key, defaultVal string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return defaultVal
}

func getEnvBool(key string, defaultVal bool) bool {
	v := os.Getenv(key)
	if v == "" {
		return defaultVal
	}
	return v == "y" || v == "yes" || v == "true" || v == "1"
}

func generatePassword(length int) string {
	b := make([]byte, length)
	rand.Read(b)
	return base64.RawURLEncoding.EncodeToString(b)[:length]
}
