import { Router } from 'express';
const router = Router();

import authRoutes from './auth';
import projectRoutes from './projects';
import deploymentRoutes from './deployments';
import configRoutes from './config';
import secretRoutes from './secrets';
import storageRoutes from './storage';
import alertRoutes from './alerts';
import dbConnectionRoutes from './db-connections';
import bootstrapRoutes from './bootstrap';
import webhookRoutes from './webhooks';
import cicdRoutes from './cicd';
import sdkRoutes from './sdk';
import metricRoutes from './metrics';
import settingRoutes from './settings';
import auditLogRoutes from './audit-logs';
import bugReportRoutes from './bug-reports';
import dbProvisionRoutes from './db-provision';

router.use('/', authRoutes);
router.use('/', projectRoutes);
router.use('/', deploymentRoutes);
router.use('/', configRoutes);
router.use('/', secretRoutes);
router.use('/', storageRoutes);
router.use('/', alertRoutes);
router.use('/', dbConnectionRoutes);
router.use('/', bootstrapRoutes);
router.use('/', webhookRoutes);
router.use('/', cicdRoutes);
router.use('/', sdkRoutes);
router.use('/', metricRoutes);
router.use('/', settingRoutes);
router.use('/', auditLogRoutes);
router.use('/', bugReportRoutes);
router.use('/', dbProvisionRoutes);

export default router;
